// Signature Collection - Premium & Exclusive Cards
// "Where unforgettable moments begin"

export const signatureTemplates = {
  wedding: [
    {
      id: 'royal-maharaja',
      name: 'Royal Maharaja',
      category: 'Luxury Wedding',
      collection: 'Signature',
      description: 'Regal Indian wedding with royal elegance',
      colors: {
        primary: '#FFD700',
        secondary: '#8B0000',
        accent: '#FFA500',
        text: '#FFFFFF',
      },
      preview: '👑',
      isPremium: true,
    },
    {
      id: 'pearl-palace',
      name: 'Pearl Palace',
      category: 'Luxury Wedding',
      collection: 'Signature',
      description: 'Opulent palace-inspired design',
      colors: {
        primary: '#E6E6FA',
        secondary: '#9370DB',
        accent: '#4B0082',
        text: '#2C2C2C',
      },
      preview: '🏰',
      isPremium: true,
    },
    {
      id: 'diamond-dreams',
      name: 'Diamond Dreams',
      category: 'Luxury Wedding',
      collection: 'Signature',
      description: 'Luxurious diamond-inspired elegance',
      colors: {
        primary: '#B9F2FF',
        secondary: '#FFFFFF',
        accent: '#00CED1',
        text: '#1C1C1C',
      },
      preview: '💎',
      isPremium: true,
    },
    {
      id: 'golden-heritage',
      name: 'Golden Heritage',
      category: 'Luxury Wedding',
      collection: 'Signature',
      description: 'Traditional Indian heritage with modern touch',
      colors: {
        primary: '#FFD700',
        secondary: '#FFA500',
        accent: '#FF6347',
        text: '#2C2C2C',
      },
      preview: '🕌',
      isPremium: true,
    },
    {
      id: 'velvet-royalty',
      name: 'Velvet Royalty',
      category: 'Luxury Wedding',
      collection: 'Signature',
      description: 'Luxurious velvet-inspired design',
      colors: {
        primary: '#800020',
        secondary: '#4B0000',
        accent: '#FFD700',
        text: '#FFFFFF',
      },
      preview: '🎭',
      isPremium: true,
    },
  ],
  engagement: [
    {
      id: 'royal-engagement-gold',
      name: 'Royal Engagement Gold',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Majestic engagement celebration',
      colors: {
        primary: '#FFD700',
        secondary: '#FFF8DC',
        accent: '#B8860B',
        text: '#2C2C2C',
      },
      preview: '💍👑',
      isPremium: true,
    },
    {
      id: 'diamond-ring',
      name: 'Diamond Ring',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Elegant diamond ring design',
      colors: {
        primary: '#E0E0E0',
        secondary: '#FFFFFF',
        accent: '#C0C0C0',
        text: '#1C1C1C',
      },
      preview: '💍✨',
      isPremium: true,
    },
    {
      id: 'rose-gold-romance',
      name: 'Rose Gold Romance',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Romantic rose gold elegance',
      colors: {
        primary: '#E8B4B8',
        secondary: '#F5E6D3',
        accent: '#D4AF37',
        text: '#4A4A4A',
      },
      preview: '🌹💍',
      isPremium: true,
    },
    {
      id: 'emerald-elegance',
      name: 'Emerald Elegance',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Luxurious emerald green design',
      colors: {
        primary: '#50C878',
        secondary: '#E8F5E9',
        accent: '#2E7D32',
        text: '#1C1C1C',
      },
      preview: '💚💍',
      isPremium: true,
    },
    {
      id: 'sapphire-serenity',
      name: 'Sapphire Serenity',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Calm and elegant sapphire blue',
      colors: {
        primary: '#0F52BA',
        secondary: '#E6F2FF',
        accent: '#00308F',
        text: '#FFFFFF',
      },
      preview: '💙💍',
      isPremium: true,
    },
    {
      id: 'pearl-perfection',
      name: 'Pearl Perfection',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Classic pearl white elegance',
      colors: {
        primary: '#F8F6F0',
        secondary: '#FFFFFF',
        accent: '#E8E8E8',
        text: '#2C2C2C',
      },
      preview: '🤍💍',
      isPremium: true,
    },
    {
      id: 'amethyst-dreams',
      name: 'Amethyst Dreams',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Mystical purple amethyst design',
      colors: {
        primary: '#9966CC',
        secondary: '#E6E6FA',
        accent: '#663399',
        text: '#FFFFFF',
      },
      preview: '💜💍',
      isPremium: true,
    },
    {
      id: 'coral-bliss',
      name: 'Coral Bliss',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Vibrant coral pink celebration',
      colors: {
        primary: '#FF7F50',
        secondary: '#FFE4E1',
        accent: '#FF6347',
        text: '#2C2C2C',
      },
      preview: '🧡💍',
      isPremium: true,
    },
    {
      id: 'ivory-classic',
      name: 'Ivory Classic',
      category: 'Royal Engagement',
      collection: 'Signature',
      description: 'Timeless ivory and gold',
      colors: {
        primary: '#FFFFF0',
        secondary: '#FFFEF0',
        accent: '#D4AF37',
        text: '#2C2C2C',
      },
      preview: '🤍👑',
      isPremium: true,
    },
  ],
  anniversary: [
    {
      id: 'golden-jubilee',
      name: 'Golden Jubilee',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Celebrate golden moments',
      colors: {
        primary: '#FFD700',
        secondary: '#FFFACD',
        accent: '#FFA500',
        text: '#2C2C2C',
      },
      preview: '🥇',
      isPremium: true,
    },
    {
      id: 'silver-celebration',
      name: 'Silver Celebration',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Elegant silver anniversary design',
      colors: {
        primary: '#C0C0C0',
        secondary: '#F5F5F5',
        accent: '#808080',
        text: '#2C2C2C',
      },
      preview: '🥈',
      isPremium: true,
    },
    {
      id: 'ruby-romance',
      name: 'Ruby Romance',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Passionate ruby red celebration',
      colors: {
        primary: '#E0115F',
        secondary: '#FFE4E1',
        accent: '#8B0000',
        text: '#FFFFFF',
      },
      preview: '💎❤️',
      isPremium: true,
    },
    {
      id: 'platinum-perfection',
      name: 'Platinum Perfection',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Timeless platinum elegance',
      colors: {
        primary: '#E5E4E2',
        secondary: '#F8F8FF',
        accent: '#BCC6CC',
        text: '#1C1C1C',
      },
      preview: '💠',
      isPremium: true,
    },
    {
      id: 'crystal-celebration',
      name: 'Crystal Celebration',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Sparkling crystal clear elegance',
      colors: {
        primary: '#F0F8FF',
        secondary: '#FFFFFF',
        accent: '#B0E0E6',
        text: '#1C1C1C',
      },
      preview: '💎✨',
      isPremium: true,
    },
    {
      id: 'copper-charm',
      name: 'Copper Charm',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Warm copper anniversary design',
      colors: {
        primary: '#B87333',
        secondary: '#F4E4BC',
        accent: '#8B4513',
        text: '#FFFFFF',
      },
      preview: '🟤💝',
      isPremium: true,
    },
    {
      id: 'lavender-love',
      name: 'Lavender Love',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Soft lavender romantic design',
      colors: {
        primary: '#E6E6FA',
        secondary: '#F5F5F5',
        accent: '#9370DB',
        text: '#2C2C2C',
      },
      preview: '💜🌺',
      isPremium: true,
    },
    {
      id: 'sunset-glow',
      name: 'Sunset Glow',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Warm sunset orange celebration',
      colors: {
        primary: '#FF7F50',
        secondary: '#FFE4B5',
        accent: '#FF6347',
        text: '#2C2C2C',
      },
      preview: '🌅💕',
      isPremium: true,
    },
    {
      id: 'midnight-elegance',
      name: 'Midnight Elegance',
      category: 'Designer Anniversary',
      collection: 'Signature',
      description: 'Sophisticated midnight blue',
      colors: {
        primary: '#191970',
        secondary: '#2F2F4F',
        accent: '#000080',
        text: '#FFFFFF',
      },
      preview: '🌙💙',
      isPremium: true,
    },
  ],
};

// Get all signature templates
export const getAllSignatureTemplates = () => {
  return [
    ...signatureTemplates.wedding,
    ...signatureTemplates.engagement,
    ...signatureTemplates.anniversary,
  ];
};

// Get templates by type
export const getSignatureTemplatesByType = (type) => {
  return signatureTemplates[type] || [];
};

// Get template by ID
export const getSignatureTemplateById = (templateId) => {
  const allTemplates = getAllSignatureTemplates();
  return allTemplates.find((template) => template.id === templateId);
};

