// Premium Wedding Card Templates
// 25-30 premium templates for modern digital wedding invitations

export const weddingTemplates = [
  {
    id: 'elegant-rose-gold',
    name: 'Elegant Rose Gold',
    category: 'Elegant',
    description: 'Classic elegance with rose gold accents',
    colors: {
      primary: '#D4AF37',
      secondary: '#F5E6D3',
      accent: '#8B4513',
      text: '#2C2C2C',
    },
    preview: '🌹✨',
  },
  {
    id: 'modern-minimalist',
    name: 'Modern Minimalist',
    category: 'Modern',
    description: 'Clean lines and sophisticated simplicity',
    colors: {
      primary: '#1A1A1A',
      secondary: '#FFFFFF',
      accent: '#E8E8E8',
      text: '#2C2C2C',
    },
    preview: '⚪',
  },
  {
    id: 'romantic-blush',
    name: 'Romantic Blush',
    category: 'Romantic',
    description: 'Soft blush tones for a romantic celebration',
    colors: {
      primary: '#F8BBD0',
      secondary: '#FFF0F5',
      accent: '#DDA0DD',
      text: '#4A4A4A',
    },
    preview: '💕',
  },
  {
    id: 'golden-luxury',
    name: 'Golden Luxury',
    category: 'Luxury',
    description: 'Opulent gold design for a lavish affair',
    colors: {
      primary: '#FFD700',
      secondary: '#FFFACD',
      accent: '#B8860B',
      text: '#2C2C2C',
    },
    preview: '👑',
  },
  {
    id: 'vintage-floral',
    name: 'Vintage Floral',
    category: 'Vintage',
    description: 'Timeless vintage with botanical elements',
    colors: {
      primary: '#8B7355',
      secondary: '#F5F5DC',
      accent: '#DEB887',
      text: '#3E2723',
    },
    preview: '🌸',
  },
  {
    id: 'beach-sunset',
    name: 'Beach Sunset',
    category: 'Destination',
    description: 'Tropical vibes with sunset colors',
    colors: {
      primary: '#FF6B6B',
      secondary: '#FFE66D',
      accent: '#4ECDC4',
      text: '#2C2C2C',
    },
    preview: '🌴',
  },
  {
    id: 'snow-white',
    name: 'Snow White',
    category: 'Winter',
    description: 'Elegant winter wonderland theme',
    colors: {
      primary: '#FFFFFF',
      secondary: '#F0F0F0',
      accent: '#B0C4DE',
      text: '#1C1C1C',
    },
    preview: '❄️',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    category: 'Luxury',
    description: 'Regal purple for a majestic celebration',
    colors: {
      primary: '#6B46C1',
      secondary: '#EDE9FE',
      accent: '#A855F7',
      text: '#FFFFFF',
    },
    preview: '💜',
  },
  {
    id: 'garden-party',
    name: 'Garden Party',
    category: 'Garden',
    description: 'Fresh and vibrant garden celebration',
    colors: {
      primary: '#10B981',
      secondary: '#D1FAE5',
      accent: '#34D399',
      text: '#1F2937',
    },
    preview: '🌺',
  },
  {
    id: 'moonlight-silver',
    name: 'Moonlight Silver',
    category: 'Elegant',
    description: 'Shimmering silver under moonlit skies',
    colors: {
      primary: '#C0C0C0',
      secondary: '#F8F8F8',
      accent: '#708090',
      text: '#2C2C2C',
    },
    preview: '🌙',
  },
  {
    id: 'sunshine-yellow',
    name: 'Sunshine Yellow',
    category: 'Bright',
    description: 'Radiant yellow for a joyful day',
    colors: {
      primary: '#FCD34D',
      secondary: '#FEF3C7',
      accent: '#F59E0B',
      text: '#1F2937',
    },
    preview: '☀️',
  },
  {
    id: 'pearl-white',
    name: 'Pearl White',
    category: 'Classic',
    description: 'Timeless pearl white elegance',
    colors: {
      primary: '#F5F5F5',
      secondary: '#FFFFFF',
      accent: '#E5E5E5',
      text: '#333333',
    },
    preview: '🔔',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    category: 'Romantic',
    description: 'Delicate cherry blossom spring theme',
    colors: {
      primary: '#FFB6C1',
      secondary: '#FFF0F5',
      accent: '#FF69B4',
      text: '#4A4A4A',
    },
    preview: '🌸',
  },
  {
    id: 'rustic-barn',
    name: 'Rustic Barn',
    category: 'Rustic',
    description: 'Charming rustic barn wedding style',
    colors: {
      primary: '#8B4513',
      secondary: '#DEB887',
      accent: '#A0522D',
      text: '#2C2C2C',
    },
    preview: '🌾',
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    category: 'Destination',
    description: 'Tranquil ocean-inspired elegance',
    colors: {
      primary: '#0EA5E9',
      secondary: '#E0F2FE',
      accent: '#0284C7',
      text: '#FFFFFF',
    },
    preview: '🌊',
  },
  {
    id: 'lavender-dreams',
    name: 'Lavender Dreams',
    category: 'Romantic',
    description: 'Dreamy lavender fields theme',
    colors: {
      primary: '#A78BFA',
      secondary: '#EDE9FE',
      accent: '#8B5CF6',
      text: '#4A4A4A',
    },
    preview: '🌷',
  },
  {
    id: 'ivory-cream',
    name: 'Ivory Cream',
    category: 'Classic',
    description: 'Sophisticated ivory and cream tones',
    colors: {
      primary: '#FFFEF0',
      secondary: '#FFFACD',
      accent: '#F0E68C',
      text: '#3E2723',
    },
    preview: '📜',
  },
  {
    id: 'midnight-elegance',
    name: 'Midnight Elegance',
    category: 'Luxury',
    description: 'Dramatic midnight blue sophistication',
    colors: {
      primary: '#1E3A8A',
      secondary: '#1E40AF',
      accent: '#3B82F6',
      text: '#FFFFFF',
    },
    preview: '🌃',
  },
  {
    id: 'sakura-pink',
    name: 'Sakura Pink',
    category: 'Romantic',
    description: 'Japanese-inspired sakura blossoms',
    colors: {
      primary: '#FFB6C1',
      secondary: '#FFE4E1',
      accent: '#FF69B4',
      text: '#4A4A4A',
    },
    preview: '🎌',
  },
  {
    id: 'emerald-green',
    name: 'Emerald Green',
    category: 'Nature',
    description: 'Rich emerald green natural beauty',
    colors: {
      primary: '#059669',
      secondary: '#D1FAE5',
      accent: '#10B981',
      text: '#FFFFFF',
    },
    preview: '💚',
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'Destination',
    description: 'Vibrant coral tropical paradise',
    colors: {
      primary: '#FF7F50',
      secondary: '#FFE4E1',
      accent: '#FF6347',
      text: '#FFFFFF',
    },
    preview: '🐚',
  },
  {
    id: 'champagne-gold',
    name: 'Champagne Gold',
    category: 'Elegant',
    description: 'Celebratory champagne and gold',
    colors: {
      primary: '#F7E7CE',
      secondary: '#FFFEF0',
      accent: '#D4AF37',
      text: '#3E2723',
    },
    preview: '🥂',
  },
  {
    id: 'peachy-keen',
    name: 'Peachy Keen',
    category: 'Bright',
    description: 'Warm peach tones for summer love',
    colors: {
      primary: '#FFDAB9',
      secondary: '#FFF8DC',
      accent: '#FFA07A',
      text: '#4A4A4A',
    },
    preview: '🍑',
  },
  {
    id: 'sage-green',
    name: 'Sage Green',
    category: 'Nature',
    description: 'Calming sage green serenity',
    colors: {
      primary: '#9CAF88',
      secondary: '#F5F5DC',
      accent: '#8FBC8F',
      text: '#2C2C2C',
    },
    preview: '🌿',
  },
  {
    id: 'starry-night',
    name: 'Starry Night',
    category: 'Romantic',
    description: 'Romantic starry night sky theme',
    colors: {
      primary: '#191970',
      secondary: '#1E3A8A',
      accent: '#4169E1',
      text: '#FFFFFF',
    },
    preview: '⭐',
  },
  {
    id: 'terracotta-warmth',
    name: 'Terracotta Warmth',
    category: 'Rustic',
    description: 'Warm terracotta earth tones',
    colors: {
      primary: '#E2725B',
      secondary: '#FFF5E6',
      accent: '#CD5C5C',
      text: '#2C2C2C',
    },
    preview: '🏺',
  },
  {
    id: 'blush-nude',
    name: 'Blush Nude',
    category: 'Modern',
    description: 'Contemporary blush and nude palette',
    colors: {
      primary: '#E8C5B0',
      secondary: '#FFF8F3',
      accent: '#D4A574',
      text: '#3E2723',
    },
    preview: '🎀',
  },
  {
    id: 'crimson-romance',
    name: 'Crimson Romance',
    category: 'Romantic',
    description: 'Bold crimson red passion',
    colors: {
      primary: '#DC143C',
      secondary: '#FFE4E1',
      accent: '#B22222',
      text: '#FFFFFF',
    },
    preview: '❤️',
  },
  {
    id: 'forest-magic',
    name: 'Forest Magic',
    category: 'Nature',
    description: 'Enchanted forest mystical theme',
    colors: {
      primary: '#2F5233',
      secondary: '#E8F5E9',
      accent: '#4A7C59',
      text: '#FFFFFF',
    },
    preview: '🌲',
  },
  {
    id: 'copper-rose',
    name: 'Copper Rose',
    category: 'Modern',
    description: 'Modern copper and rose combination',
    colors: {
      primary: '#B87333',
      secondary: '#FFE4E1',
      accent: '#CD853F',
      text: '#2C2C2C',
    },
    preview: '🌹',
  },
  {
    id: 'whimsical-pastel',
    name: 'Whimsical Pastel',
    category: 'Bright',
    description: 'Playful pastel rainbow colors',
    colors: {
      primary: '#FFB6C1',
      secondary: '#E0F7FA',
      accent: '#C8A2C8',
      text: '#4A4A4A',
    },
    preview: '🎈',
  },
  {
    id: 'marble-sophistication',
    name: 'Marble Sophistication',
    category: 'Luxury',
    description: 'Elegant marble-inspired design',
    colors: {
      primary: '#E5E5E5',
      secondary: '#FFFFFF',
      accent: '#C0C0C0',
      text: '#2C2C2C',
    },
    preview: '🏛️',
  },
  {
    id: 'traditional-indian',
    name: 'Traditional Indian',
    category: 'Traditional',
    description: 'Classic Indian wedding with ornate borders and traditional motifs',
    colors: {
      primary: '#D4A574',
      secondary: '#FFF8F0',
      accent: '#8B4513',
      text: '#2C2C2C',
    },
    preview: '🕉️',
  },
];

// Helper function to get template by ID
export const getTemplateById = (templateId) => {
  return weddingTemplates.find((template) => template.id === templateId) || weddingTemplates[0];
};

// Get templates by category
export const getTemplatesByCategory = (category) => {
  return weddingTemplates.filter((template) => template.category === category);
};

// Get all unique categories
export const getCategories = () => {
  return [...new Set(weddingTemplates.map((template) => template.category))];
};


