// Premium Wedding Card Templates
// 20 premium templates with beautiful background images

export const weddingTemplates = [
  // Premium Templates with Unique Background Images
  {
    id: 'opulent-mandap-indoor',
    name: 'Opulent Mandap - Indoor',
    category: 'Luxury',
    description: 'Magnificent indoor mandap with crystal chandelier and lavish floral decorations',
    colors: {
      primary: '#FFD700',
      secondary: '#FFF8DC',
      accent: '#FFA500',
      text: '#FFFFFF',
    },
    preview: '💎',
    backgroundImage: '/images/wedding-backgrounds/opulent-mandap-indoor.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'palace-mandap-outdoor',
    name: 'Palace Mandap - Outdoor',
    category: 'Heritage',
    description: 'Elegant outdoor mandap with traditional palace architecture backdrop',
    colors: {
      primary: '#DC143C',
      secondary: '#FFF8DC',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '🏛️',
    backgroundImage: '/images/wedding-backgrounds/palace-mandap-outdoor.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'sunset-palace-wedding',
    name: 'Sunset Palace Wedding',
    category: 'Romantic',
    description: 'Romantic sunset wedding setup with mandap and palace backdrop',
    colors: {
      primary: '#FF6B6B',
      secondary: '#FFE66D',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '🌅',
    backgroundImage: '/images/wedding-backgrounds/sunset-palace-wedding.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'dusk-garden-mandap',
    name: 'Dusk Garden Mandap',
    category: 'Romantic',
    description: 'Magical dusk wedding with illuminated canopy and garden setting',
    colors: {
      primary: '#9370DB',
      secondary: '#E6E6FA',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '✨',
    backgroundImage: '/images/wedding-backgrounds/dusk-garden-mandap.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'golden-temple-golden-hour',
    name: 'Golden Temple - Golden Hour',
    category: 'Traditional',
    description: 'Beautiful Golden Temple at golden hour with warm lighting',
    colors: {
      primary: '#FFD700',
      secondary: '#FFF8DC',
      accent: '#FFA500',
      text: '#FFFFFF',
    },
    preview: '🕉️',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'golden-temple-soft-light',
    name: 'Golden Temple - Soft Light',
    category: 'Traditional',
    description: 'Serene Golden Temple with soft morning light',
    colors: {
      primary: '#87CEEB',
      secondary: '#E0F7FA',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '🕉️',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-soft-light.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'bougainvillea-archway',
    name: 'Bougainvillea Archway',
    category: 'Elegant',
    description: 'Elegant archway adorned with vibrant pink bougainvillea',
    colors: {
      primary: '#FF69B4',
      secondary: '#FFF0F5',
      accent: '#FF1493',
      text: '#FFFFFF',
    },
    preview: '🌸',
    backgroundImage: '/images/wedding-backgrounds/bougainvillea-archway.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'fortified-city-rajasthan',
    name: 'Fortified City - Rajasthan',
    category: 'Heritage',
    description: 'Majestic fortified city on hillside with traditional architecture',
    colors: {
      primary: '#D2691E',
      secondary: '#FFF8DC',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '🏰',
    backgroundImage: '/images/wedding-backgrounds/fortified-city.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'traditional-wedding-couple',
    name: 'Traditional Wedding Couple',
    category: 'Traditional',
    description: 'Beautiful traditional Indian wedding couple in grand architecture',
    colors: {
      primary: '#DC143C',
      secondary: '#FFF8DC',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '💑',
    backgroundImage: '/images/wedding-backgrounds/traditional-wedding-couple.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'traditional-indian',
    name: 'Traditional Indian',
    category: 'Traditional',
    description: 'Classic Indian wedding with ornate borders and traditional motifs',
    colors: {
      primary: '#D4A574',
      secondary: '#FFF8F0',
      accent: '#8B4513',
      text: '#2C2C2C',
    },
    preview: '🕉️',
    backgroundImage: '/images/wedding-backgrounds/traditional-wedding-couple.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'sikh-anand-karaj',
    name: 'Sikh Anand Karaj',
    category: 'Traditional',
    description: 'Traditional Sikh wedding with Gurbani text and couple illustration',
    colors: {
      primary: '#87CEEB',
      secondary: '#E0F7FA',
      accent: '#FFA500',
      text: '#1A1A1A',
    },
    preview: '🕊️',
    hasCouple: true,
    backgroundType: 'image',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    hasGurbani: true,
    hasOverlay: true,
  },
  {
    id: 'hindu-wedding-ceremony',
    name: 'Hindu Wedding Ceremony',
    category: 'Traditional',
    description: 'Traditional Hindu wedding with Ganesha, red roses, and elegant floral borders',
    colors: {
      primary: '#DC143C',
      secondary: '#FFFFFF',
      accent: '#FFD700',
      text: '#8B0000',
    },
    preview: '🕉️',
    hasCouple: true,
    backgroundType: 'image',
    backgroundImage: '/images/wedding-backgrounds/hindu-template.jpeg',
    hasHindu: true,
    hasOverlay: false,
  },
  {
    id: 'elegant-rose-gold',
    name: 'Elegant Rose Gold',
    category: 'Elegant',
    description: 'Classic elegance with rose gold accents',
    colors: {
      primary: '#D4AF37',
      secondary: '#F5E6D3',
      accent: '#8B4513',
      text: '#2C2C2C',
    },
    preview: '🌹✨',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'golden-luxury',
    name: 'Golden Luxury',
    category: 'Luxury',
    description: 'Opulent gold design for a lavish affair',
    colors: {
      primary: '#FFD700',
      secondary: '#FFFACD',
      accent: '#B8860B',
      text: '#2C2C2C',
    },
    preview: '👑',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'romantic-blush',
    name: 'Romantic Blush',
    category: 'Romantic',
    description: 'Soft blush tones for a romantic celebration',
    colors: {
      primary: '#F8BBD0',
      secondary: '#FFF0F5',
      accent: '#DDA0DD',
      text: '#4A4A4A',
    },
    preview: '💕',
    backgroundImage: '/images/wedding-backgrounds/bougainvillea-archway.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'vintage-floral',
    name: 'Vintage Floral',
    category: 'Vintage',
    description: 'Timeless vintage with botanical elements',
    colors: {
      primary: '#8B7355',
      secondary: '#F5F5DC',
      accent: '#DEB887',
      text: '#3E2723',
    },
    preview: '🌸',
    backgroundImage: '/images/wedding-backgrounds/traditional-wedding-couple.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'premium-couple-golden',
    name: 'Premium Couple Golden',
    category: 'Premium',
    description: 'Elegant couple illustration with golden accents and floral background',
    colors: {
      primary: '#D4AF37',
      secondary: '#FFF8DC',
      accent: '#FFD700',
      text: '#2C2C2C',
    },
    preview: '👰🤵',
    hasCouple: true,
    backgroundType: 'image',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    hasOverlay: true,
  },
  {
    id: 'premium-couple-romantic',
    name: 'Premium Couple Romantic',
    category: 'Romantic',
    description: 'Romantic couple design with soft pink and rose background',
    colors: {
      primary: '#FFB6C1',
      secondary: '#FFF0F5',
      accent: '#FF69B4',
      text: '#4A4A4A',
    },
    preview: '💑',
    hasCouple: true,
    backgroundType: 'image',
    backgroundImage: '/images/wedding-backgrounds/bougainvillea-archway.jpg',
    hasOverlay: true,
  },
  {
    id: 'luxury-couple-elegant',
    name: 'Luxury Couple Elegant',
    category: 'Luxury',
    description: 'Luxurious couple illustration with elegant gold and white design',
    colors: {
      primary: '#FFFFFF',
      secondary: '#F5F5F5',
      accent: '#D4AF37',
      text: '#1A1A1A',
    },
    preview: '💍',
    hasCouple: true,
    backgroundType: 'image',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-soft-light.jpg',
    hasOverlay: true,
  },
  {
    id: 'modern-minimalist',
    name: 'Modern Minimalist',
    category: 'Modern',
    description: 'Clean lines and sophisticated simplicity',
    colors: {
      primary: '#1A1A1A',
      secondary: '#FFFFFF',
      accent: '#E8E8E8',
      text: '#2C2C2C',
    },
    preview: '⚪',
    backgroundImage: '/images/wedding-backgrounds/fortified-city.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  // Premium Luxury Templates
  {
    id: 'royal-maharaja-premium',
    name: 'Royal Maharaja Premium',
    category: 'Luxury',
    description: 'Regal Indian wedding with royal elegance and opulent design',
    colors: {
      primary: '#FFD700',
      secondary: '#8B0000',
      accent: '#FFA500',
      text: '#FFFFFF',
    },
    preview: '👑',
    backgroundImage: '/images/wedding-backgrounds/opulent-mandap-indoor.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'pearl-palace-premium',
    name: 'Pearl Palace Premium',
    category: 'Luxury',
    description: 'Opulent palace-inspired design with pearl accents',
    colors: {
      primary: '#E6E6FA',
      secondary: '#9370DB',
      accent: '#4B0082',
      text: '#2C2C2C',
    },
    preview: '🏰',
    backgroundImage: '/images/wedding-backgrounds/palace-mandap-outdoor.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'diamond-dreams-premium',
    name: 'Diamond Dreams Premium',
    category: 'Luxury',
    description: 'Luxurious diamond-inspired elegance with sparkling design',
    colors: {
      primary: '#B9F2FF',
      secondary: '#FFFFFF',
      accent: '#00CED1',
      text: '#1C1C1C',
    },
    preview: '💎',
    backgroundImage: '/images/wedding-backgrounds/dusk-garden-mandap.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'golden-heritage-premium',
    name: 'Golden Heritage Premium',
    category: 'Heritage',
    description: 'Traditional Indian heritage with modern premium touch',
    colors: {
      primary: '#FFD700',
      secondary: '#FFA500',
      accent: '#FF6347',
      text: '#2C2C2C',
    },
    preview: '🕌',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-golden-hour.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'velvet-royalty-premium',
    name: 'Velvet Royalty Premium',
    category: 'Luxury',
    description: 'Luxurious velvet-inspired design with royal elegance',
    colors: {
      primary: '#800020',
      secondary: '#4B0000',
      accent: '#FFD700',
      text: '#FFFFFF',
    },
    preview: '🎭',
    backgroundImage: '/images/wedding-backgrounds/sunset-palace-wedding.png',
    backgroundType: 'image',
    hasOverlay: true,
  },
  {
    id: 'platinum-elegance-premium',
    name: 'Platinum Elegance Premium',
    category: 'Luxury',
    description: 'Sophisticated platinum and white elegance',
    colors: {
      primary: '#E5E4E2',
      secondary: '#FFFFFF',
      accent: '#C0C0C0',
      text: '#1C1C1C',
    },
    preview: '✨',
    backgroundImage: '/images/wedding-backgrounds/golden-temple-soft-light.jpg',
    backgroundType: 'image',
    hasOverlay: true,
  },
];

// Helper function to get template by ID
export const getTemplateById = (templateId) => {
  return weddingTemplates.find((template) => template.id === templateId) || weddingTemplates[0];
};

// Get templates by category
export const getTemplatesByCategory = (category) => {
  return weddingTemplates.filter((template) => template.category === category);
};

// Get all unique categories
export const getCategories = () => {
  const categories = [...new Set(weddingTemplates.map((template) => template.category))];
  return categories.sort();
};

// Alias for backward compatibility
export const getTemplateCategories = getCategories;
